name: wdb106_sample
description: A new Flutter project.
version: 1.0.0+1
dependencies:
  flutter:
    sdk: flutter
  disposable_provider:
  flutter_state_notifier:
  freezed_annotation:
  mono_kit: ^0.14.0-dev
  provider: ^4.1.0-dev
  rxdart:
  simple_logger:
  state_notifier:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  image_test_utils:
  json_serializable:
  mockito:
  pedantic_mono:
flutter:
  uses-material-design: true