name: wdb106_sample
description: A new Flutter project.
version: 1.0.0+1
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: '>=0.16.0'
  freezed_annotation:
  hooks_riverpod: ^0.14.0
  http:
  simple_logger:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: '>=0.13.0'
  image_test_utils:
    git:
      url: https://github.com/mono0926/image_test_utils.git
      ref: add-compressionState
  json_serializable:
  mockito:
  pedantic_mono:
flutter:
  uses-material-design: true
environment:
  sdk: '>=2.12.0'
  flutter: '>=1.22.0'
