name: wdb106_sample
description: A new Flutter project.
version: 1.0.0+1
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  hooks_riverpod:
  flutter_hooks:
  simple_logger:
  disposable_provider:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  image_test_utils:
    git:
      url: https://github.com/mono0926/image_test_utils.git
      ref: add-compressionState
  json_serializable:
  mockito:
  pedantic_mono:
flutter:
  uses-material-design: true